### ISSUE TITLE
Incorrect use of logging

### ISSUE THREAD

**Issue by extreme4all** [NeverScapeAlone/NeverScapeAlone-API#55]
when logging you should use the logger object: (logger) 
https://github.com/NeverScapeAlone/NeverScapeAlone-API/blob/2ba6262e809fe89b8eae1a8fe7b7d07ba8f205eb/api/routers/lobbies.py#L41
instead of logging
https://github.com/NeverScapeAlone/NeverScapeAlone-API/blob/2ba6262e809fe89b8eae1a8fe7b7d07ba8f205eb/api/routers/lobbies.py#L77

**Comment by Ferrariic** [comment]
tyvm will be reworked in v2.2.0-alpha
